spring.application.name=securityDemo
# static password and user for the default spring security
spring.security.user.name=user
spring.security.user.password=admin

logging.level.root=INFO
logging.level.com.yourpackage=DEBUG
